node_js:
- '4.2'
language: node_js
before_install:
- chmod +x -R build
- git config --global user.email "${GIT_EMAIL}"
- git config --global user.name "${GIT_NAME}";
install:
- npm install
script:
- npm run-script build
- npm test
after_success:
- "./build/repo-cli.sh"
deploy:
  skip_cleanup: true
  provider: npm
  email: todd@deepelement.com
  api_key:
    secure: RNA2o5EWhzLTzYw85cjr6S3pTKc2JrQnITojjnSgnyzPIk5ETQ84hP24o3dLmjxLGkdlTW0ee6cgRTXBXX93SbK37Of1IL7ot6gRCw/1x5sN4qH3ePWZ+fiP7rIad8fDi9FE4AhQBlE8PuRp+ZTDPfsibR6uFKcua0Oi7A89DA3cniK2VQSSpRRCNjuGFzDWGnwqJSXBlMdScNMnDU5YTe5Z9u/H2JwD4fMDbg2Yz4IDNN3ToYvbn8WS3hliHhZs0AOXwGYlkx9nIHs9LY1wvo+5uDJn69Xeqo8pwPBkDfRU4iKLnsINjQLyQYcIKjrxpHlzyuXmMORij+7x9ohjIEC6Z5g++Tu2YFpW3cmPDCuZr8PbT2ExZxYQPaG2g+HglCdYhgw+Douakx8Wj1hJbzcbOjRI+44P8QCzosN+gLE/s0/k8zHBXuI1puIdPrb0eIa6Wwzc+8hsIEvybxcxYPeYB1heOJyhcdVmWkYb4Pm0kShNeSXVzp+DgWwNCSyiiCyPaMrT37DmdnjNP5YuJenBqpTab3AcSCpHW79e1ZABks2J5xvI+vrzcKA7sF0ZXGDu1iuWoS92hEqaOHBnJGpuzMyCrtAM3eSIxRmkv1qqMWqH/tK2f/Y/hj21BT5ufWEtgSIwFdTZ3g1UWCvFUUXbnHMDX0tXLcZc0uHb5/U=
  on:
    tags: true
    repo: DeepElement/winjsrocks-plugin-platform
